(function(){"use strict";var STORE_KEY="wingLedger";var START_BALANCE=1000;var STAKE_STEP=5;var STAKE_MAX=100000;var HAZARD_BASE=0.16;var HAZARD_RAMP=0.03;var HAZARD_CEIL=0.55;var FLIGHT_CAP=25;var TAKEOFF_TIME=0.9;var LANDING_TIME=1.1;var SPLASH_TIME=1.4;var GAUGE_MULT_TOP=5;var canvas=document.getElementById("wing-sky");var ledgerEl=document.getElementById("wing-ledger-view");var refillEl=document.getElementById("wing-refill");var stakeEl=document.getElementById("wing-stake");var stakeDownEl=document.getElementById("wing-stake-down");var stakeUpEl=document.getElementById("wing-stake-up");var takeoffEl=document.getElementById("wing-takeoff");var landEl=document.getElementById("wing-land");var radioEl=document.getElementById("wing-radio");var multNeedleEl=document.getElementById("wing-mult-needle");var multViewEl=document.getElementById("wing-mult-view");var riskNeedleEl=document.getElementById("wing-risk-needle");var riskViewEl=document.getElementById("wing-risk-view");var haulViewEl=document.getElementById("wing-haul-view");var flagStripEl=document.getElementById("wing-flag-strip");if(!canvas||!canvas.getContext||!ledgerEl||!stakeEl||!takeoffEl||!landEl||!radioEl||!multNeedleEl||!riskNeedleEl||!flagStripEl){return;}
var ctx=canvas.getContext("2d");var view={w:640,h:360};var sim={phase:"idle",balance:loadBalance(),stake:0,mult:1,airTime:0,phaseTime:0,planeX:0,planeY:0,pitch:0,landFromY:0,flags:[],spawnIn:1.2,clock:0,rafOn:false,lastTs:0};var effects=[];function loadBalance(){var raw=null;try{raw=window.localStorage.getItem(STORE_KEY);}catch(err){raw=null;}
if(raw===null||raw===""){return START_BALANCE;}
var num=Number(raw);if(!isFinite(num)||num<0){return START_BALANCE;}
return cents(num);}
function saveBalance(){try{window.localStorage.setItem(STORE_KEY,String(sim.balance));}catch(err){return;}}
function cents(value){return Math.round(value*100)/100;}
function money(value){var v=cents(value);return v===Math.floor(v)?String(v):v.toFixed(2);}
function say(text,mood){radioEl.textContent=text;radioEl.classList.remove("good","bad");if(mood){radioEl.classList.add(mood);}}
function paintLedger(){ledgerEl.textContent=money(sim.balance);}
function paintDials(){var multFrac=Math.min(1,(sim.mult-1)/(GAUGE_MULT_TOP-1));multNeedleEl.style.transform="rotate("+(multFrac*180-90).toFixed(1)+"deg)";multViewEl.textContent=sim.mult.toFixed(2)+"×";var hazard=sim.phase==="airborne"?HAZARD_BASE+HAZARD_RAMP*sim.airTime:0;var riskFrac=Math.min(1,hazard/HAZARD_CEIL);riskNeedleEl.style.transform="rotate("+(riskFrac*180-90).toFixed(1)+"deg)";riskViewEl.textContent=Math.round(riskFrac*100)+"%";if(sim.phase==="airborne"||sim.phase==="takeoff"){haulViewEl.textContent=money(sim.stake*sim.mult);}else if(sim.phase==="idle"){haulViewEl.textContent="—";}}
function lockControls(flying){stakeEl.disabled=flying;stakeDownEl.disabled=flying;stakeUpEl.disabled=flying;refillEl.disabled=flying;takeoffEl.disabled=flying;landEl.disabled=sim.phase!=="airborne";}
function addFlagChip(value){var chip=document.createElement("span");chip.className="wing-flag-chip-4d3fbc82";chip.textContent="+"+value.toFixed(1)+"×";flagStripEl.appendChild(chip);}
function readStake(){var v=Math.floor(Number(stakeEl.value));return isFinite(v)?v:0;}
function clampStake(){var v=readStake();if(v<1){v=1;}
if(v>STAKE_MAX){v=STAKE_MAX;}
stakeEl.value=String(v);}
function nudgeStake(delta){if(sim.phase!=="idle"){return;}
stakeEl.value=String(readStake());stakeEl.value=String(Math.min(STAKE_MAX,Math.max(1,readStake()+delta)));}
function takeOff(){if(sim.phase!=="idle"){return;}
clampStake();var stake=readStake();if(stake<1){say("The tower needs a stake of at least 1.","bad");return;}
if(stake>sim.balance){say("That stake is heavier than your ledger.","bad");return;}
sim.stake=stake;sim.balance=cents(sim.balance-stake);saveBalance();paintLedger();sim.mult=1;sim.airTime=0;sim.phaseTime=0;sim.flags=[];sim.spawnIn=0.9+Math.random()*0.8;sim.phase="takeoff";flagStripEl.innerHTML="";lockControls(true);paintDials();say("Throttle up — climbing out over the water.","");wake();}
function landNow(){if(sim.phase!=="airborne"){return;}
var haul=cents(sim.stake*sim.mult);sim.balance=cents(sim.balance+haul);saveBalance();paintLedger();sim.phase="landing";sim.phaseTime=0;sim.landFromY=sim.planeY;landEl.disabled=true;say("Floats down — banked "+money(haul)+" at "+
sim.mult.toFixed(2)+"×.","good");}
function splashDown(){sim.phase="splash";sim.phaseTime=0;landEl.disabled=true;say("Splash! The sea kept your "+money(sim.stake)+" stake.","bad");}
function settle(){sim.phase="idle";sim.flags=[];lockControls(false);paintDials();if(sim.balance<1){say("Ledger is empty — press Refill to fuel a new demo run.","bad");}}
function refill(){if(sim.phase!=="idle"){return;}
sim.balance=START_BALANCE;saveBalance();paintLedger();say("Ledger topped back up to "+START_BALANCE+".","");}
function step(dt){sim.clock+=dt;sim.phaseTime+=dt;var cruiseY=view.h*0.42;var bobAmp=view.h*0.07;var seaY=view.h*0.78;var homeX=view.w*0.3;if(sim.phase==="takeoff"){var k=Math.min(1,sim.phaseTime/TAKEOFF_TIME);var e=1-(1-k)*(1-k);sim.planeX=view.w*0.16+(homeX-view.w*0.16)*e;sim.planeY=(seaY-14)+(cruiseY-(seaY-14))*e;sim.pitch=-0.22*(1-k);if(k>=1){sim.phase="airborne";sim.airTime=0;landEl.disabled=false;say("Airborne. Catch flags, then press Land in time.","");}}else if(sim.phase==="airborne"){sim.airTime+=dt;sim.planeX=homeX;sim.planeY=cruiseY+Math.sin(sim.clock*1.7)*bobAmp;sim.pitch=Math.cos(sim.clock*1.7)*0.06;moveFlags(dt,seaY);var hazard=HAZARD_BASE+HAZARD_RAMP*sim.airTime;if(sim.airTime>FLIGHT_CAP||Math.random()<hazard*dt){splashDown();}
paintDials();}else if(sim.phase==="landing"){var lk=Math.min(1,sim.phaseTime/LANDING_TIME);var le=lk*lk*(3-2*lk);sim.planeX=homeX+view.w*0.12*le;sim.planeY=sim.landFromY+
((seaY-14)-sim.landFromY)*le;sim.pitch=0.12*(1-Math.abs(1-2*lk));moveFlags(dt,seaY);if(lk>=1){settle();}}else if(sim.phase==="splash"){if(sim.planeY<seaY-4){sim.pitch=Math.min(0.9,sim.pitch+dt*2.2);sim.planeY+=(140+320*sim.phaseTime)*dt*(view.h/360);sim.planeX+=40*dt*(view.w/640);if(sim.planeY>=seaY-4){sim.planeY=seaY-4;burst(sim.planeX,seaY);}}
moveFlags(dt,seaY);if(sim.phaseTime>=SPLASH_TIME){settle();}}
for(var i=effects.length-1;i>=0;i-=1){effects[i].age+=dt;if(effects[i].age>=effects[i].life){effects.splice(i,1);}}}
function moveFlags(dt,seaY){var speed=view.w*0.22;if(sim.phase==="airborne"){sim.spawnIn-=dt;if(sim.spawnIn<=0){sim.spawnIn=1.6+Math.random()*0.8;var cruiseY=view.h*0.42;var band=view.h*0.07;var y=Math.random()<0.7?cruiseY+(Math.random()*2-1)*band*0.8:cruiseY+(Math.random()*2-1)*band*2.6;y=Math.min(seaY-44,Math.max(view.h*0.14,y));sim.flags.push({x:view.w+40,y:y,v:(2+Math.floor(Math.random()*7))/10});}}
for(var i=sim.flags.length-1;i>=0;i-=1){var f=sim.flags[i];f.x-=speed*dt;if(sim.phase==="airborne"&&Math.abs(f.x-sim.planeX)<34&&Math.abs(f.y-sim.planeY)<30){sim.mult=cents(sim.mult+f.v);addFlagChip(f.v);ring(f.x,f.y);sim.flags.splice(i,1);}else if(f.x<-60){sim.flags.splice(i,1);}}}
function ring(x,y){effects.push({kind:"ring",x:x,y:y,age:0,life:0.5});}
function burst(x,y){effects.push({kind:"foam",x:x,y:y,age:0,life:0.9});for(var i=0;i<14;i+=1){effects.push({kind:"drop",x:x,y:y,vx:(Math.random()*2-1)*130,vy:-60-Math.random()*180,age:0,life:0.7+Math.random()*0.3});}}
function paint(){var w=view.w;var h=view.h;var seaY=h*0.78;var sky=ctx.createLinearGradient(0,0,0,seaY);sky.addColorStop(0,"#8ec9ef");sky.addColorStop(1,"#eaf7ff");ctx.fillStyle=sky;ctx.fillRect(0,0,w,seaY);ctx.fillStyle="rgba(255, 255, 255, 0.85)";paintCloud(mod(w*0.15-sim.clock*9,w+220)-110,h*0.16,1);paintCloud(mod(w*0.55-sim.clock*14,w+220)-110,h*0.3,0.75);paintCloud(mod(w*0.85-sim.clock*6,w+220)-110,h*0.09,1.2);var sea=ctx.createLinearGradient(0,seaY,0,h);sea.addColorStop(0,"#1191ac");sea.addColorStop(1,"#123a63");ctx.fillStyle=sea;ctx.fillRect(0,seaY,w,h-seaY);ctx.strokeStyle="rgba(255, 255, 255, 0.5)";ctx.lineWidth=1.5;for(var r=0;r<3;r+=1){var wy=seaY+8+r*((h-seaY)/3.4);ctx.beginPath();for(var x=-20;x<=w+20;x+=8){var y=wy+Math.sin(x*0.045+sim.clock*1.4+r*2)*2.4;if(x===-20){ctx.moveTo(x,y);}else{ctx.lineTo(x,y);}}
ctx.stroke();}
for(var i=0;i<sim.flags.length;i+=1){paintFlag(sim.flags[i]);}
for(var e=0;e<effects.length;e+=1){paintEffect(effects[e]);}
var splashed=sim.phase==="splash"&&sim.phaseTime>SPLASH_TIME*0.6;if(!splashed){paintPlane(sim.planeX,sim.planeY,sim.pitch);}}
function mod(v,m){return((v%m)+m)%m;}
function paintCloud(x,y,s){ctx.beginPath();ctx.ellipse(x,y,42*s,14*s,0,0,Math.PI*2);ctx.ellipse(x+26*s,y-8*s,26*s,12*s,0,0,Math.PI*2);ctx.ellipse(x-28*s,y-5*s,22*s,10*s,0,0,Math.PI*2);ctx.fill();}
function paintFlag(f){ctx.strokeStyle="#123a63";ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(f.x,f.y-20);ctx.lineTo(f.x,f.y+16);ctx.stroke();ctx.beginPath();ctx.arc(f.x,f.y-26,7,0,Math.PI*2);ctx.fillStyle="#ffffff";ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(f.x,f.y-14);ctx.lineTo(f.x+26,f.y-8);ctx.lineTo(f.x,f.y-2);ctx.closePath();ctx.fillStyle="#c8963e";ctx.fill();ctx.fillStyle="#123a63";ctx.font="600 11px 'Public Sans', sans-serif";ctx.textAlign="left";ctx.fillText("+"+f.v.toFixed(1),f.x+4,f.y+30);}
function paintEffect(fx){var k=fx.age/fx.life;if(fx.kind==="ring"){ctx.strokeStyle="rgba(200, 150, 62, "+(1-k).toFixed(2)+")";ctx.lineWidth=3;ctx.beginPath();ctx.arc(fx.x,fx.y,8+k*30,0,Math.PI*2);ctx.stroke();}else if(fx.kind==="foam"){ctx.fillStyle="rgba(255, 255, 255, "+(0.8*(1-k)).toFixed(2)+")";ctx.beginPath();ctx.ellipse(fx.x,fx.y,16+k*46,7+k*12,0,0,Math.PI*2);ctx.fill();}else{var t=fx.age;var dx=fx.x+fx.vx*t;var dy=fx.y+fx.vy*t+340*t*t;ctx.fillStyle="rgba(240, 250, 255, "+(1-k).toFixed(2)+")";ctx.beginPath();ctx.arc(dx,dy,2.6,0,Math.PI*2);ctx.fill();}}
function paintPlane(x,y,pitch){ctx.save();ctx.translate(x,y);ctx.rotate(pitch);ctx.fillStyle="#123a63";ctx.beginPath();ctx.ellipse(0,0,26,9,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-24,-2);ctx.lineTo(-34,-16);ctx.lineTo(-26,-16);ctx.lineTo(-16,-4);ctx.closePath();ctx.fill();ctx.fillStyle="#c8963e";ctx.beginPath();ctx.moveTo(-6,-4);ctx.lineTo(6,-4);ctx.lineTo(14,-14);ctx.lineTo(2,-14);ctx.closePath();ctx.fill();ctx.strokeStyle="#c8963e";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-8,8);ctx.lineTo(-8,15);ctx.moveTo(8,8);ctx.lineTo(8,15);ctx.stroke();ctx.fillStyle="#123a63";ctx.beginPath();ctx.ellipse(0,17,20,4,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#bfe3f7";ctx.beginPath();ctx.ellipse(9,-3,6,4,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle="rgba(18, 58, 99, 0.7)";ctx.lineWidth=2.5;var spin=sim.clock*32;ctx.beginPath();ctx.moveTo(26+Math.cos(spin)*2,Math.sin(spin)*12);ctx.lineTo(26-Math.cos(spin)*2,-Math.sin(spin)*12);ctx.stroke();ctx.restore();}
function frame(ts){if(!sim.lastTs){sim.lastTs=ts;}
var dt=Math.min(0.05,(ts-sim.lastTs)/1000);sim.lastTs=ts;step(dt);paint();if(sim.phase==="idle"&&effects.length===0){sim.rafOn=false;sim.lastTs=0;restPose();paint();return;}
window.requestAnimationFrame(frame);}
function wake(){if(!sim.rafOn){sim.rafOn=true;sim.lastTs=0;window.requestAnimationFrame(frame);}}
function restPose(){sim.planeX=view.w*0.16;sim.planeY=view.h*0.78-14;sim.pitch=0;}
function fitCanvas(){var box=canvas.parentNode;var w=Math.max(280,Math.min(box.clientWidth-2,860));var h=Math.round(Math.min(400,Math.max(220,w*0.55)));var dpr=window.devicePixelRatio||1;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);canvas.style.width=w+"px";canvas.style.height=h+"px";ctx.setTransform(dpr,0,0,dpr,0,0);view.w=w;view.h=h;if(sim.phase==="idle"){restPose();paint();}}
takeoffEl.addEventListener("click",takeOff);landEl.addEventListener("click",landNow);refillEl.addEventListener("click",refill);stakeDownEl.addEventListener("click",function(){nudgeStake(-STAKE_STEP);});stakeUpEl.addEventListener("click",function(){nudgeStake(STAKE_STEP);});stakeEl.addEventListener("change",clampStake);window.addEventListener("resize",fitCanvas);fitCanvas();paintLedger();paintDials();lockControls(false);if(sim.balance<1){say("Ledger is empty — press Refill to fuel a new demo run.","");}})();